version: '3'

services:
  mocky:
    build: ./docker
    container_name: mocky
    volumes:
      - ./scripts:/app/scripts
      - ./files:/app/files
    ports:
      - "${MOCKY_PORT:-3000}:3000"
    command: node scripts/mocky.js
